# Generated by Django 4.0.1 on 2024-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasTanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_type', models.CharField(blank=True, choices=[('10', '10'), ('13', '13'), ('25', '25')], max_length=2)),
            ],
        ),
    ]
