# Generated by Django 4.0.1 on 2024-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_gastanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastanks',
            name='tank_status',
            field=models.CharField(choices=[('F', 'Full'), ('E', 'Empty')], default='Full', max_length=1),
        ),
    ]
