# Generated by Django 4.0.1 on 2024-05-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
