# Generated by Django 4.0.1 on 2024-05-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_remove_question_likes_remove_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_type', models.CharField(blank=True, choices=[('10', '10'), ('13', '13'), ('25', '25')], max_length=2)),
                ('price', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
    ]
