# Generated by Django 4.0.1 on 2024-05-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_alter_gastanks_tank_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastanks',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testApp.pricetanks'),
        ),
    ]
