# Generated by Django 4.0.1 on 2024-05-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_gastanks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastanks',
            name='price',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.pricetanks'),
        ),
    ]
