# Generated by Django 4.0.1 on 2024-06-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_question_gastanks_alter_pricetanks_tank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gastanks',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='testApp.warehouse'),
        ),
    ]
